### PR TITLE
Clean up group.toml

### PR DESCRIPTION
**Pull request by ineiti**
Deleting not usable servers.

### CODE REVIEW

**Comment by nikkolasg** [comment]
Mhhh. Do you still think it makes sense to maintain a cothority for v0 ?

**Comment by ineiti** [comment]
If we don't, then we can delete the whole cosi-repository and all references to v0. If we keep references to v0, let's have a usable cothority.

**Comment by nikkolasg** [comment]
Ok right. What's happening with Travis !?

**Comment by ineiti** [comment]
There were some `github.com/dedis/cothority/network`-imports, and they fail now. Updated the imports to point to `cothority.v0`.

**Comment by ineiti** [comment]
And `cosi.v0` fails with race-check on go-1.7.3... so moved back to go 1.6. I think that's reasonable, as we don't really use it anymore...

**Comment by nikkolasg** [comment]
Ok that's fine with me as we now start focusing our efforts on the `dedis/cothority` version.

**Pull request merged**
